<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>图书借阅系统Web端</title>
</head>
<body>
	<div align="center">
		<table border="0" width="800" id="table1" height="429">
			<tr>
			<td colspan="2" height="90" bgcolor="#CCFFFF">
				<p align="center">
					<font size="5">--读者书刊借阅记录自助查询--</font></p>
				<p>
			</td>
		</tr>  
		<tr>
			<td width="18%" valign='top' bgcolor="#D3D3D3">
				<p><a href="List.aspx?op=logint" onclick="return confirm('确认重新进入吗？')">登录</a></p>
				<p><a href="List.aspx">借阅记录</a></p>
				<p><a href="Information.aspx">书刊信息</a></p>
				<p><a href="Default.aspx?op=logout" onclick="return confirm('确认注销吗？')">注销</a></p>
				<p></p>
				<p>
			</td>
			<td width="80%" bgcolor="#CCFFCC" valign="top">